export const NAMES = [
    "Aarav Mehta",
    "Diya Sharma",
    "Rohan Patel",
    "Ananya Iyer",
    "Kabir Singh",
    "Ishita Verma",
    "Ayaan Nair",
    "Mira Joshi",
    "Vihaan Rao",
    "Tanya Kapoor",
    "Aditya Khanna",
    "Sanya Bhatia",
    "Arjun Deshmukh",
    "Kavya Reddy",
    "Nikhil Sood",
    "Riya Malhotra",
    "Harsh Chauhan",
    "Neha Pillai",
    "Karan Thakur",
    "Sneha Ghosh",
    "Aryan Gupta",
    "Simran Kaur",
    "Devansh Menon",
    "Priya Chatterjee",
    "Reyansh Dutta",
    "Ira Mahajan",
    "Ritvik Tiwari",
    "Aditi Chauhan",
    "Rahul Jain",
    "Esha Bansal",
    "Vivaan Kaul",
    "Anika Sharma",
    "Manav Reddy",
    "Pooja Nambiar",
    "Krish Patel",
    "Sakshi Mehta",
    "Parth Agarwal",
    "Avni Sen",
    "Dhruv Bhatnagar",
    "Mitali Das",
  ];
  
  export const COMMENTS = [
    "The sunset over the mountains looks absolutely breathtaking and peaceful today.",
    "Loved how the trees danced with the wind in this video.",
    "The sound of flowing water instantly calms my mind every single time.",
    "Nature never fails to remind us how small yet connected we are.",
    "The colors of the sky blend so perfectly, it feels almost unreal.",
    "Such a soothing clip, makes me want to take a long forest walk.",
    "That moment when sunlight hit the lake surface was pure cinematic magic.",
    "This video captures the raw beauty and stillness of untouched wilderness perfectly.",
    "Every frame feels like a painting come alive, so peaceful and serene.",
    "The chirping birds and rustling leaves are the best natural background music.",
    "Watching this makes me want to escape city noise and live near nature.",
    "The camera work and sound design together made this feel deeply immersive.",
    "Incredible how a simple breeze through trees can evoke so much calmness.",
    "This feels like therapy for the eyes, heart, and soul altogether.",
    "Can’t believe how beautiful Earth is when we actually take a moment.",
    "The waterfall scene reminded me of childhood trips to hill stations.",
    "Each second of this felt like a deep breath after a long day.",
    "Nature videos like this should be played in every stressful workspace daily.",
    "I could loop this forever and still not get tired of it.",
    "There’s something magical about how sunlight filters through dense green forests.",
    "Reminds me to slow down and appreciate the little details around me.",
    "That golden hour lighting across the fields was nothing short of heavenly.",
    "You captured tranquility so beautifully; this could be a wallpaper gallery.",
    "The balance between water, wind, and earth is just mesmerizing to watch.",
    "Every drop of rain in this video feels like music from nature itself.",
    "Loved how the mist slowly covered the valley, looked so cinematic.",
    "This video makes me realize how healing silence and stillness can be.",
    "I wish I could teleport there right now and just breathe deeply.",
    "Absolutely stunning! Reminds me of early morning hikes in Himachal Pradesh.",
    "The transition from dusk to night was captured so gracefully, pure art.",
    "That rainbow reflection on water gave me instant peace and happiness.",
    "Videos like this remind us why we must protect our planet more.",
    "Those tiny ripples on the pond added such life to the frame.",
    "Could watch this loop endlessly while sipping tea on a rainy day.",
    "The blend of colors in this forest trail feels straight out of dream.",
    "Nature doesn’t need filters — this proves it in the most beautiful way.",
    "Everything about this — the light, the shadows, the sound — feels divine.",
    "You’ve captured serenity in motion, every shot feels meditative and grounding.",
    "This makes me want to unplug everything and just sit by the lake.",
    "The clouds moving slowly behind those peaks felt surreal and almost poetic.",
  ];
  
  export const ICONS = [
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIf4R5qPKHPNMyAqV-FjS_OTBB8pfUV29Phg&s",
    "https://cdn-icons-png.flaticon.com/512/4128/4128244.png",
    "https://cdn-icons-png.flaticon.com/512/4128/4128309.png",
    "https://cdn-icons-png.flaticon.com/512/1486/1486111.png",
    "https://cdn-icons-png.flaticon.com/512/3003/3003062.png",
    "https://cdn-icons-png.flaticon.com/512/1305/1305712.png",
    "https://cdn-icons-png.flaticon.com/256/3003/3003035.png",
    "https://cdn-icons-png.flaticon.com/512/4715/4715328.png",
    "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    "https://cdn-icons-png.flaticon.com/512/3135/3135789.png",
    "https://cdn-icons-png.flaticon.com/512/4537/4537097.png",
  ];
  